---
- hosts: beaker
  vars_files:
    - vault.yaml 
  tasks:
    - name: Subscribing beaker machine to CDN and attaching a pool which provides OpenStack repositories
      redhat_subscription:
        state: present
        username: "{{username}}"
        password: "{{password}}"
        auto_attach: true
        pool_ids: 8a85f9815bb07800015bb08408ba11f0

#    - name: Disable all RHSM repositories
#      rhsm_repository:
#        name: '*'
#        state: disabled    

#    - name: Enabling required repositories
#      rhsm_repository:
#        name: ['rhel-7-server-rpms', 'rhel-7-server-extras-rpms', 'rhel-7-server-rh-common-rpms', 'rhel-ha-for-rhel-7-server-rpms', 'rhel-7-server-openstack-13-rpms']
#        state: enabled 

    - name: Install libvirt packages packages
      yum:
        name: ['libvirt-client', 'libvirt-daemon', 'qemu-kvm', 'libvirt-daemon-driver-qemu', 'libvirt-daemon-kvm', 'virt-install', 'bridge-utils', 'openvswitch', 'libguestfs-tools', 'net-tools', 'libguestfs-xfs', 'net-tools', 'python-setuptools', 'ipmitool', 'python-virtualbmc', 'wget']
        state: latest

    - name: Starting libvirtd and openvswitch services
      systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - 'libvirtd'
        - 'openvswitch'

    - name: Enablinglibvirtd and openvswitch services
      systemd:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - 'libvirtd'
        - 'openvswitch'

    - name: Creating softlinks for /home/images
      shell: |
        cd /var/lib/libvirt
        rm -rf images
        mkdir /home/images
        chcon -t virt_image_t /home/images
        ln -s /home/images .
 
    - name: Fetching RHEL 7 KVM image
      get_url:
        url: http://file.pnq.redhat.com/~ykulkarn/kvm-images/rhel-server-7.7-update-1-x86_64-kvm.qcow2
        dest: /home/images
